#FROM python:3.10-slim
#
#
#
#
#
#WORKDIR /app
#
#COPY . /app
#
#
#RUN pip install flask
#
#EXPOSE 5000
#
#
#
#CMD ["python", "app.py"]

# Use Python official image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy project files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose port (optional)
EXPOSE 5000

# Start Flask app
CMD ["python", "app.py"]
